[BIOMAGE-2071] - Install Datadog as sidecar
biomage-org/pipeline pull request #30
Opened 2022-09-21 15:30 UTC by aerlaut

# Description
- Install Datadog container as sidecar
- Add permissions required for Datadog sidecar to deployment runner service account in Kubernetes cluster. 

https://ui-agi-worker24-pipeline30.scp-staging.biomage.net/

#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-2071

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR
N/A

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-09-30 12:46 UTC, kafkasl requested changes

2022-09-30 12:46 UTC, kafkasl commented on chart-infra/templates/datadog-sidecar-rbac.yaml
> +kind: ClusterRoleBinding
this will not work as intended. The cluster roles must be unique across the whole cluster. Adding it this way means that we will try to re-create it every time we deploy the pipeline again and the deployments will fail. You can either:

1. Restrict it's deployment only to the default environment like in api/cluster-autoscaler-autodiscover.yaml
2. Put this file somewhere it's deployed only once like `iac/infra`

2022-09-30 12:54 UTC, aerlaut commented on chart-infra/templates/datadog-sidecar-rbac.yaml
> +kind: ClusterRoleBinding
The ClusterRole is unique - `datadog-sidecar-rbac`. It is currently manually created in the cluster, but it'll be added from IAC. I have this PR out to add that: https://github.com/biomage-org/iac/pull/22/files#diff-61c1f805162c2cf7170df9bc62178cbc0ee7a96d9bf47c5abcce1900016214ae. The PR itself is quite big, so I think I'll split it out to make the deployment in stages.

We need a role binding for every deployment runner because they are scoped in different namespaces. To make the RoleBinding unique, I used the release namespace (e.g.. worker-agi-datadog) at the end of each role binding.

2022-09-30 13:03 UTC, aerlaut commented on chart-infra/templates/datadog-sidecar-rbac.yaml
> +kind: ClusterRoleBinding
Split out the ClusterRole definition in this PR: https://github.com/biomage-org/iac/pull/33

2022-09-30 13:07 UTC, kafkasl approved these changes

2022-09-30 13:21 UTC, ivababukova requested changes
This whole thing needs to be changed to happen only for pods in the Biomage account.

2022-09-30 17:27 UTC, ivababukova commented on chart-infra/templates/datadog-sidecar-rbac.yaml
> +kind: ClusterRoleBinding
do we need one ClusterRole binding for pipeline and one separate one for each worker deployment?

2022-10-04 08:22 UTC, aerlaut commented on chart-infra/templates/datadog-sidecar-rbac.yaml
> +kind: ClusterRoleBinding
Yes, because they're in different namespaces.

2022-10-04 11:07 UTC, aerlaut commented on chart-infra/templates/datadog-sidecar-rbac.yaml
> +kind: ClusterRoleBinding
The alternative to this is to create a ClusterRoleBinding resource, e.g. `datadog-sidecar-bindings`, and then add the various `deployment-runners` in the different namespaces into this ClusterRoleBinding. However, this is more difficult to do because we'll need to do an an update of `datadog-sidecar-bindings` to add/remove bindings to the proper namespace when we stage/unstage. We need to ensure that staging/unstaging does not affect the other values.

If we create a different cluster-role-binding for deployment-runners for each namespace, we can just add/delete when staging/unstaging, isolating the changes for the deployment-runners in the other namespaces.

2022-10-04 12:55 UTC, ivababukova approved these changes

2022-10-05 18:39 UTC, ivababukova commented on chart-infra/templates/pipeline-spawn-right-to-api.yaml
> -- apiGroups: [""]
could you revert the changes here and have the file as it was?

2022-10-05 18:40 UTC, ivababukova commented on chart-infra/templates/cleanup-operator-roles.yaml
> -  - list
Can you revert these changes and leave the file as it was? I see that there are only fomatting changes here

2022-10-06 06:27 UTC, ivababukova approved these changes

2022-10-07 09:15 UTC, merged