Geometric sketching
biomage-org/pipeline pull request #36
Opened 2022-10-03 09:50 UTC by saracastel

# Description
Test geometric sketching to assess if it will allow us to process much bigger datasets. This PR performs: geosketch on each sample, merge and integrate the sketches with harmony, learn the transformation and apply it to the rest of the dataset.

# Details
#### URL to issue
N/A

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-10-12 13:06 UTC, gerbeldo requested changes

2022-10-12 13:09 UTC, gerbeldo commented on pipeline-runner/Dockerfile
> +
it should suffice to have this in the common minimal build. But check if that's the case, in the scVI PR  it might have been left repeated without meaning to.

2022-10-13 06:34 UTC, ivababukova commented on pipeline-runner/Dockerfile
> +    ln -s /src/r-miniconda/envs/r-reticulate/lib/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
have you checked if we need this?

2022-10-13 06:40 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +# datasets_int: list of sketched integrated datasets
Instead of adding comments on what the variables are, I would change theis names to make it obvious what they are. In particular, you can name them:
`unsketched_data` - original unsketched list of datasets
`sketched_data_list` - list of sketched datasets
`sketched_integrated_data` -list of sketched integrated datasets
Question about them is: is only the second one a list? Or are all of them lists?

2022-10-13 06:42 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +import numpy as np
why is this file written in python instead of R? And if it needs to be in Python, why is it not done from the Python part of the worker? If we do it from the python part, we wouldn't need to have reticulate_python

2022-10-13 06:44 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +    labels = np.array(labels, dtype=int)
is this line needed? I don't see variable `labels` used anymore

2022-10-13 06:50 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +        X_int = datasets_int[i]
small, thing, but I would move the initialisation of `X_init` lower, as close to where it is used as possible. It makes the code easier to read. Best, but it just before you initialise `bias`.

2022-10-13 06:54 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +# datasets_int: list of sketched integrated datasets
Looking at the code, seems like they are all lists. In this case, either add `_list` at the end of each of them, or do not add `_list` to the end of neither of them.

2022-10-13 07:15 UTC, saracastel commented on pipeline-runner/Dockerfile
> +    R -e "reticulate::conda_install('r-reticulate', 'scanorama', pip = TRUE)" && \
Right, I cleaned the dockerfile. Not sure how come I was installing reticulate from conda...

2022-10-13 07:17 UTC, saracastel commented on pipeline-runner/Dockerfile
> +
I removed it from both places. It seems it was not needed

2022-10-13 07:18 UTC, saracastel commented on pipeline-runner/Dockerfile
> +    ln -s /src/r-miniconda/envs/r-reticulate/lib/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
yes, I tried removing it and everything seems to work fine. Removed it

2022-10-13 08:27 UTC, saracastel commented on pipeline-runner/Dockerfile
> +    R -e "reticulate::conda_install('r-reticulate', 'scanorama', pip = TRUE)" && \
This is not actually installing reticulate from conda, but "r-reticulate" is the `envname` parameter of the `conda_install` [function](https://rstudio.github.io/reticulate/reference/conda-tools.html). So it's installing geosketch in the r-reticulate environment.

If I clean the dockerfile as in [this commit](https://github.com/biomage-org/pipeline/pull/36/commits/ff7811980ba6827534179bd795e094b5f071aea1) it will build successfully, but when setting geomsketch = TRUE [here](https://github.com/biomage-org/pipeline/blob/ff7811980ba6827534179bd795e094b5f071aea1/pipeline-runner/R/qc-6-integrate_scdata.R#L23) 
the pipeline will fail with error `No module named 'geosketch'` when doing `reticulate::import("geosketch")` from the pipeline.

Also, I agree that geosketch should be imported in the function that uses it, but I'm not sure why, if I remove `R -e "geosketch <- reticulate::import('geosketch')" && \` from the dockerfile, the build will fail.

2022-10-13 08:34 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +from scipy.sparse import csr_matrix, find
Right, some imports were left from a longer script. I removed the unused ones. But I left numpy as it's used [here](https://github.com/biomage-org/pipeline/blob/ff7811980ba6827534179bd795e094b5f071aea1/pipeline-runner/R/learn-apply-transformation.py#L20), and transform from scanorama which is used [here](https://github.com/biomage-org/pipeline/blob/ff7811980ba6827534179bd795e094b5f071aea1/pipeline-runner/R/learn-apply-transformation.py#L34)

2022-10-13 08:37 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +integrate_scdata <- function(scdata_list, config, sample_id, cells_id, task_name = "dataIntegration", geomsketch = FALSE, perc_num_cells = 5) {
Makes sense. Renamed it

2022-10-13 09:10 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +# datasets_int: list of sketched integrated datasets
Makes sense. They are all lists, so I renamed it without specifying "list" in the variable names, to avoid making the names too long

2022-10-13 09:23 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +    labels = np.array(labels, dtype=int)
good catch, this was a leftover from a longer script. Removed it

2022-10-13 09:27 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +        X_int = datasets_int[i]
Right, moved it.

2022-10-13 09:28 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +from scipy.sparse import csr_matrix, find
Actually, I removed also numpy as the piece of code that was using it was not used as well

2022-10-13 09:50 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +import numpy as np
It's because it was the quickest and easiest way to implement it in the platform, as the Python scripts are already provided by the authors of the [geosketch paper](https://www.sciencedirect.com/science/article/pii/S2405471219301528). I think it could be done in R, but it would require more time to translate it... not sure if it'd be worth it.
As to why it's not done from the Python part of the worker, it's because it has to be run as part of the integration step which is done in the pipeline, so I don't think it could be done in the worker. But maybe I'm wrong

2022-10-13 10:27 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  }
I have refactored it. It was also duplicated. Moved it only [here](https://github.com/biomage-org/pipeline/blob/b3616abb42458f26e14d3ce90b814c2991cad4c0/pipeline-runner/R/qc-6-integrate_scdata.R#L188)

2022-10-13 10:31 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata_sketches = ""
I think so, otherwise it will complain about not finding `scdata_sketches` [here](https://github.com/biomage-org/pipeline/blob/b3616abb42458f26e14d3ce90b814c2991cad4c0/pipeline-runner/R/qc-6-integrate_scdata.R#L40) when geosketch = F

2022-10-13 14:42 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  }
Done. Extracting it from the integrated seurat object is indeed easier

2022-10-13 14:43 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  }
yep, it was sufficient to add it [here](https://github.com/biomage-org/pipeline/blob/54151fd325b6f3954b6731672511c2d3f4aa83df/pipeline-runner/R/qc-6-integrate_scdata.R#L641) at the end of `learn_from_sketches`

2022-10-13 14:56 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  stopifnot(ncol(object@reductions[[reduction]]) >= dims)
Done

2022-10-14 07:16 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +    for i, (X_unsketch, X_sketch) in enumerate(zip(unsketched_data, sketched_data)):
how about `X_sketched` and `X_unsketched`?

2022-10-14 07:17 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +        ds_idxs, ref_idxs = [], []
what is `ds_idxs` and `ref_idxs`?

2022-10-14 07:19 UTC, ivababukova commented on pipeline-runner/R/qc-6-integrate_scdata.R
>  #   },
is this comment still relevant and in the right format?

2022-10-14 07:19 UTC, ivababukova commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +integrate_scdata <- function(scdata_list, config, sample_id, cells_id, task_name = "dataIntegration", geosketch = FALSE, perc_num_cells = 5) {
what is `perc_num_cells`?

2022-10-14 07:21 UTC, ivababukova commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +integrate_scdata <- function(scdata_list, config, sample_id, cells_id, task_name = "dataIntegration", geosketch = FALSE, perc_num_cells = 5) {
you can rename `geosketch` to `use_geosketch` to make it obvious that this is a boolean.

2022-10-14 08:12 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +integrate_scdata <- function(scdata_list, config, sample_id, cells_id, task_name = "dataIntegration", geosketch = FALSE, perc_num_cells = 5) {
Right, thanks. Done

2022-10-14 08:13 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +integrate_scdata <- function(scdata_list, config, sample_id, cells_id, task_name = "dataIntegration", geosketch = FALSE, perc_num_cells = 5) {
It's the percentage of cells that we want in the sketches. By default it's 5% of the total number of cells in each Seurat object

2022-10-14 08:30 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +        ds_idxs, ref_idxs = [], []
These come from the authors of geosketch and refer to the transform function of [scanorama](https://github.com/brianhie/scanorama/blob/master/scanorama/scanorama.py). They should be the indexes of the sketched and of the reference datasets. They are used to learn the integration transformation from the sketched dataset and apply it back to the full dataset.

2022-10-14 08:31 UTC, saracastel commented on pipeline-runner/R/learn-apply-transformation.py
> +    for i, (X_unsketch, X_sketch) in enumerate(zip(unsketched_data, sketched_data)):
yes, sounds better. Renamed them

2022-10-14 08:49 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
>  #   },
I've updated the comment trying to be consistent with the other QC steps.

2022-10-14 13:29 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    message("Started calculating sketches")
This is used only for geosketching, so it should go in the geosketching function. Like the integration methods, they all have their "set up code".

2022-10-14 13:29 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_sketches <- perform_geosketch(scdata, reduction = "pca", dims = 50, num_cells = round(ncol(scdata) * perc_num_cells / 100))
extract the num_cells variable definition, so it's cleaner

2022-10-14 13:31 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_sketches <- perform_geosketch(scdata, reduction = "pca", dims = 50, num_cells = round(ncol(scdata) * perc_num_cells / 100))
what about the number of dimensions? should it be equal to the number of principal components that users input? or hardcoded to 50? (this happens everywhere in this file though. but we should try to understand where it should and shouldn't, try to avoid hardcodings, and fix the others down the line)

2022-10-14 13:40 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    Seurat::DefaultAssay(scdata_sketches) <- "RNA"
this should be returned with the default assay set by the sketching function

2022-10-14 13:40 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +perform_geosketch <- function(object, reduction, dims, num_cells) {
object should be scdata

2022-10-14 13:52 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
>    message("Started data integration")
this would look better then 

```
scdata_sketch <- ifelse(use_geosketch,
                        perform_geosketch(scdata, reduction = "pca", dims = 50, num_cells),
                        NA)
```

2022-10-14 13:53 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_sketches <- perform_geosketch(scdata, reduction = "pca", dims = 50, num_cells = round(ncol(scdata) * perc_num_cells / 100))
also, name this var `scdata_sketch`

2022-10-14 13:54 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata_integrated <- run_dataIntegration(scdata, scdata_sketches, config, use_geosketch)
you don't need to pass `use_geosketch`, and just test `is.na(scdata_sketch)`

2022-10-14 13:59 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +perform_geosketch <- function(object, reduction, dims, num_cells) {
would be better to call this function run_geosketch, nicer than perform, and more consistent with the pipelien

2022-10-14 14:00 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    message("Finished learning from sketches")
refactor this out

2022-10-14 14:01 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_int <- integration_function(scdata_sketches, config)
scdata_sketch_integrated

2022-10-14 14:03 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  active.reduction <- scdata_int@misc[["active.reduction"]]
replace dot with underscore, to avoid annoying the R linting gods

2022-10-14 14:06 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata@misc[["active.reduction"]] <- active.reduction
shouldn't this be the key? Or does it understand it removing the underscore?

2022-10-14 14:20 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_sketches <- perform_geosketch(scdata, reduction = "pca", dims = 50, num_cells = round(ncol(scdata) * perc_num_cells / 100))
I agree, we should check where not to hardcode the number of dimensions. In this specific case I think it doesn't make much difference. This is what I understand from [here](https://github.com/brianhie/geosketch/issues/6), where the geosketch's authors say: "even if you sketch using the top 20 or 100 PCs, the "effective" number of PCs will actually be much smaller (empirically we've seen this to be around 5, or even less, on scRNA-seq datasets)."

2022-10-14 14:30 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    Seurat::DefaultAssay(scdata_sketches) <- "RNA"
Right

2022-10-17 07:47 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +perform_geosketch <- function(object, reduction, dims, num_cells) {
Done

2022-10-17 07:50 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
>    message("Started data integration")
this generates the following error: `Error in rep(yes, length.out = len) : 
  attempt to replicate an object of type 'S4'`.
I refactored it using an if/else

2022-10-17 07:51 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_sketches <- perform_geosketch(scdata, reduction = "pca", dims = 50, num_cells = round(ncol(scdata) * perc_num_cells / 100))
Done

2022-10-17 07:51 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata_integrated <- run_dataIntegration(scdata, scdata_sketches, config, use_geosketch)
Done

2022-10-17 07:52 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    message("Finished learning from sketches")
Done. You mean just `Seurat::DefaultAssay(scdata_sketches) <- "RNA"`, right?

2022-10-17 07:52 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +    scdata_int <- integration_function(scdata_sketches, config)
Done

2022-10-17 07:53 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  active.reduction <- scdata_int@misc[["active.reduction"]]
Oops. Right!

2022-10-17 07:54 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata@misc[["active.reduction"]] <- active.reduction
Not sure I fully understand what you mean, but `scdata@misc[["active.reduction"]] <- active_reduction` works. 
`"active.reduction"` is the key, which was already there, with the dot. `active_reduction` is the variable that I introduced in this PR.

2022-10-17 13:22 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata@misc[["active.reduction"]] <- active.reduction
you are creating a dimreducobject, adding it to the seurat object, using a key generated with paste0(active.reduction, "_"). And then setting the active.reduction to a different thing (without the underscore)

2022-10-17 17:49 UTC, ivababukova commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +perform_geosketch <- function(object, reduction, dims, num_cells) {
and also shorter, so shorter variable name

2022-10-17 17:53 UTC, ivababukova commented on pipeline-runner/R/learn-apply-transformation.py
> +        ds_idxs, ref_idxs = [], []
ok, so it is an internal thing that you and German and any other bioinformatician will know the meaning of?

2022-10-17 17:54 UTC, ivababukova reviewed
I don't have what else to add to the review of this PR. Leaving it to @gerbeldo to finish with the reviews and approve when the code looks good in his opinion!

2022-10-17 17:58 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +integrate_scdata <- function(scdata_list, config, sample_id, cells_id, task_name = "dataIntegration", geosketch = FALSE, perc_num_cells = 5) {
Hmmm. Maybe `subsample_proportion`? Or something along those lines. `sketch_proportion`?

2022-10-18 10:42 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  scdata@misc[["active.reduction"]] <- active.reduction
oh the key parameter is to set the names of the columns of the embeddings. Usually they are "PC_1", "PC_2", "PC3",... when the active reduction is PCA. If `active_reduction` is harmony, they will be set to  "harmony_1", "harmony_2", "harmony_3", ...

2022-10-18 13:49 UTC, gerbeldo approved these changes
looks good!

2022-10-18 14:53 UTC, merged