Implement SCTransform
biomage-org/pipeline pull request #51
Opened 2022-10-28 14:49 UTC by saracastel

# Description
Adds SCTransform as an alternative normalization method to LogNormalization. Exploit the Seurat v4 integration to integrate using Pearson residuals calculated with SCTransform.

# Details
#### URL to issue
N/A

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-11-22 20:12 UTC, gerbeldo requested changes

2022-11-22 20:12 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  }
This runs PCA twice for harmony on the first run.

2022-11-22 20:12 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  }
also for unisample

2022-11-22 20:12 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  # normalization <- "SCT" # TO REMOVE WHEN THE BUTTON IS IMPLEMENTED IN THE UI
this needs to go. irrespective of the button.

2022-11-22 20:12 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  if (method == "SCT" & Seurat::DefaultAssay(scdata) == "integrated") {
&& it's the recommended operator for guards 
```suggestion
  if (method == "SCT" && Seurat::DefaultAssay(scdata) == "integrated") {
```

2022-11-23 11:09 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  # can lead to increased run time
Ok, I wrote this base on the sctransform documentation and on comments on the github repo like [this one](https://github.com/satijalab/seurat/issues/3354). Measuring the run times with the workshop covid dataset, it's 46.293 sec with conserve.memory = F and 337.263 sec with conserve.memory = T

2022-11-23 13:05 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +}
Done

2022-11-23 13:06 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +run_sct_int_workflow <- function(data.split, reduction, normalization, k.filter, npcs) {
I renamed it to `prepare_sct_integration` as it's actually a step between SCTransform normalization and integration

2022-11-23 13:06 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  # normalization <- "SCT" # TO REMOVE WHEN THE BUTTON IS IMPLEMENTED IN THE UI
Removed

2022-11-24 08:36 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  }
right, thanks. Moved it back to after data integration

2022-11-24 17:50 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +  # can lead to increased run time
wow!

2022-11-24 17:51 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +#' \code{\link[Seurat:PrepSCTIntegration]{Seurat::PrepSCTIntegration()}},
my bad, I thought it was a typo

2022-11-24 18:31 UTC, gerbeldo approved these changes
I'm not convinced, but this requires more thought and a refactor of the integration code which, at this stage, is out of the scope of this ticket. 

You should at least create a ticket to address the number of PCs issue with more care.

2022-11-24 18:31 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +          dims = 1:npcs,
what happens if npcs is NULL? (as will happen on the first run, when we estimate, after integration the number of PCs to use).

2022-11-24 18:31 UTC, gerbeldo commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +          dims = 1:npcs,
hmm. this is not really nice. I suppose that since sctransform can't be run during the first run of the pipeline, we will have a number of PCs already estimated... It's an ugly solution honestly.

2022-11-25 09:26 UTC, saracastel commented on pipeline-runner/R/qc-6-integrate_scdata.R
> +          dims = 1:npcs,
Yeah I agree, this works only because harmony is the default method, so sctransform can't be run on the first run of the pipeline. I wrote a [ticket to refactor the #PCs estimation](https://biomage.atlassian.net/browse/BIOMAGE-2260?atlOrigin=eyJpIjoiZDQ2MjlkZDIyZjAyNGI0MDgwZDZmMDljM2Y0MTBjNWEiLCJwIjoiaiJ9).

2022-11-25 09:28 UTC, merged