[2241] Make the pipeline pass the API url as part of the message to SNS
biomage-org/pipeline pull request #68
Opened 2022-11-28 19:46 UTC by cosa65

# Description

# Details
#### URL to issue
https://biomage.atlassian.net/browse/BIOMAGE-2241

#### Link to staging deployment URL (or set N/A)

#### Links to any PRs or resources related to this PR

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-11-29 09:47 UTC, ivababukova commented on .github/workflows/ci.yaml
> +          destination_folder: "${{ steps.fill-metadata.outputs.kubernetes-env }}"
you really need to resolve those single vs double quotes differences

2022-11-29 09:50 UTC, ivababukova commented on pipeline-runner/R/init-functions.R
> +    config$api_url <- paste0("https://api.", domain_name)
Seems like with this code we will no longer use the `".svc.cluster.local:3000"` domain name. Is this true?

2022-11-29 17:44 UTC, cosa65 commented on pipeline-runner/R/init-functions.R
> +    config$api_url <- paste0("https://api.", domain_name)
After the standup feedback I am switching it back so we use the internal url when we don't use the lambda

2022-11-29 17:45 UTC, cosa65 commented on .github/workflows/ci.yaml
> +          destination_folder: "${{ steps.fill-metadata.outputs.kubernetes-env }}"
yes, the linter does it automatically although honestly I don't know if it is necessarily wrong to have linting active here, it seems like before this we had a mix of single quotes and no quotes, should I change it?

2022-11-30 08:08 UTC, kafkasl requested changes

2022-11-30 08:08 UTC, kafkasl commented on .github/workflows/ci.yaml
> +        if: (github.event_name == 'pull_request' || github.event_name == 'push') && matrix.environment == 'staging'
why this change?

2022-11-30 08:20 UTC, ivababukova reviewed
I don't understand how these changes pass in the API URL in the message to SNS -- let's talk about this over a huddle

2022-11-30 11:35 UTC, cosa65 commented on .github/workflows/ci.yaml
> +          destination_folder: "${{ steps.fill-metadata.outputs.kubernetes-env }}"
ok

2022-11-30 11:39 UTC, cosa65 commented on .github/workflows/ci.yaml
> +          destination_folder: "${{ steps.fill-metadata.outputs.kubernetes-env }}"
> which linter are you talking about?

this one:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/8465903/204786957-0febad6d-e73f-40b0-a74f-e3744db0838c.png">

2022-11-30 11:41 UTC, cosa65 commented on .github/workflows/ci.yaml
> +          destination_folder: "${{ steps.fill-metadata.outputs.kubernetes-env }}"
I set it to single quote now, let me know if it's fine

2022-11-30 11:43 UTC, cosa65 commented on .github/workflows/ci.yaml
> +        if: (github.event_name == 'pull_request' || github.event_name == 'push') && matrix.environment == 'staging'
probably more auto changes from vscode, maybe it's just easier for me to try to disable whatever kind of format on save I have right now and remove the changes in ci

2022-11-30 11:47 UTC, cosa65 commented
> I don't understand how these changes pass in the API URL in the message to SNS -- let's talk about this over a huddle

sure, in case it helps I'll write it here too:

I set `public_api_url` and then pick it up and pass it in the 3 calls to sns: (in `handle_data.R`).

2022-11-30 12:19 UTC, kafkasl commented on .github/workflows/ci.yaml
> +          destination_folder: "${{ steps.fill-metadata.outputs.kubernetes-env }}"
ok, we should try to have all the same settings using a workspace instead of custom settings

2022-12-05 14:31 UTC, ivababukova approved these changes

2022-12-06 12:05 UTC, kafkasl approved these changes

2022-12-07 13:58 UTC, merged